import argparse

from youtube_clipper.downloader import SubtitlesDownloader


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--video')
    parser.add_argument('--language', default='en')
    parser.add_argument('--allow-autogenerated', action='store_true')
    args = parser.parse_args()

    downloader = SubtitlesDownloader(language=args.language, allow_autogenerated=args.allow_autogenerated)
    print(downloader.download_subtitles(args.video))
